import {
  ActivityLogItem, CalendarEvent, CaseChangeEntry, Client, ClientUpdate, Communication, Consultation, Contact, Firm,
  Matter, MatterDocument, MatterParty, MatterTask, Notification, Referral, SubscriptionTier, TaskTemplateItem,
  TeamMember,
} from "./types";

// All names, firms, and figures below are FICTIONAL DEMONSTRATION DATA
// created for the JusticeIQ MVP walkthrough. No real persons, law firms,
// or client matters are represented. Today's demo "current date" is
// treated as 2026-08-04 for deadline/overdue framing.

export const TEAM: TeamMember[] = [
  { id: "tm-1", fullName: "Sarah Kim", email: "sarah.kim@dckllp.example", role: "partner", title: "Managing Partner", practiceAreas: ["personal_injury", "employment"], jurisdictions: ["California"], languages: ["English"], active: true, avatarInitials: "SK", capacity: 12, createdAt: "2022-01-10T09:00:00Z" },
  { id: "tm-2", fullName: "Marcus Delgado", email: "marcus.delgado@dckllp.example", role: "lawyer", title: "Senior Associate, Personal Injury", practiceAreas: ["personal_injury"], jurisdictions: ["California"], languages: ["English", "Spanish"], active: true, avatarInitials: "MD", capacity: 15, createdAt: "2022-03-01T09:00:00Z" },
  { id: "tm-3", fullName: "Priya Chandra", email: "priya.chandra@dckllp.example", role: "lawyer", title: "Senior Associate, Employment Law", practiceAreas: ["employment"], jurisdictions: ["California"], languages: ["English", "Hindi"], active: true, avatarInitials: "PC", capacity: 15, createdAt: "2022-05-15T09:00:00Z" },
  { id: "tm-4", fullName: "Jordan Wells", email: "jordan.wells@dckllp.example", role: "intake_coordinator", title: "Intake Coordinator", practiceAreas: ["personal_injury", "employment"], jurisdictions: ["California"], languages: ["English"], active: true, avatarInitials: "JW", capacity: 40, createdAt: "2023-02-01T09:00:00Z" },
  { id: "tm-5", fullName: "Emily Tran", email: "emily.tran@dckllp.example", role: "paralegal", title: "Paralegal", practiceAreas: ["personal_injury", "employment"], jurisdictions: ["California"], languages: ["English", "Vietnamese"], active: true, avatarInitials: "ET", capacity: 20, createdAt: "2023-06-01T09:00:00Z" },
  { id: "tm-6", fullName: "Alex Rivera", email: "alex.rivera@dckllp.example", role: "firm_admin", title: "Firm Administrator", practiceAreas: ["personal_injury", "employment"], jurisdictions: ["California"], languages: ["English"], active: true, avatarInitials: "AR", capacity: 0, createdAt: "2022-01-10T09:00:00Z" },
];

export const FIRM: Firm = {
  id: "firm-1",
  name: "Delgado Chandra & Kim LLP",
  practiceAreas: ["personal_injury", "employment"],
  jurisdictions: ["California"],
  offices: [
    { id: "off-1", name: "San Francisco HQ", address: "455 Market St, Suite 1900, San Francisco, CA", jurisdiction: "California" },
    { id: "off-2", name: "Oakland Satellite", address: "1300 Clay St, Suite 600, Oakland, CA", jurisdiction: "California" },
  ],
  firmSize: "11-25 attorneys and staff",
  primaryAdministratorId: "tm-6",
  languages: ["English", "Spanish", "Hindi", "Vietnamese"],
  minimumCaseCriteria: "Estimated damages above $25,000, or employment matters involving termination, discrimination, or retaliation within the last 3 years.",
  conflictScreeningProcedure: "All new referrals are screened against the firm's conflict database before consultation scheduling. Final conflict clearance is confirmed by a Partner before retainer signing.",
  consultationAvailability: "Monday-Friday, 9am-5pm Pacific; virtual consultations available same-week for urgent matters.",
  notificationPreferences: ["New referral email + in-app", "Deadline reminders 7/3/1 days out", "Daily digest of client messages"],
  subscriptionTier: "gold",
  createdAt: "2022-01-10T09:00:00Z",
};

// ---------------------------------------------------------------------
// Referrals
// ---------------------------------------------------------------------

const commonAssessmentPI = {
  claimReadiness: 78,
  informationCompleteness: 82,
  evidenceStrength: 72,
  timelineClarity: 85,
  documentAvailability: 75,
  urgency: "moderate" as const,
  aiConfidence: 80,
  identifiedUncertainties: ["Extent of long-term injury impact is not yet documented by a treating specialist.", "Comparative fault has not been formally assessed."],
  suggestedConsultationQuestions: ["What ongoing treatment is currently planned?", "Has the other driver's insurer made contact or an offer?", "Are there any prior related injuries to the same body region?"],
};

const commonAssessmentEmp = {
  claimReadiness: 74,
  informationCompleteness: 76,
  evidenceStrength: 68,
  timelineClarity: 88,
  documentAvailability: 70,
  urgency: "high" as const,
  aiConfidence: 77,
  identifiedUncertainties: ["Employer's stated reason for termination has not been formally documented in writing.", "Whether other employees were treated differently is not yet established."],
  suggestedConsultationQuestions: ["Was the Performance Improvement Plan consistent with prior documented performance?", "Who else was aware of the medical leave request?", "Has the client filed anything with a state or federal agency yet?"],
};

export const REFERRALS: Referral[] = [
  {
    id: "ref-1",
    source: "JusticeChamp Consumer Intake",
    sourceClaimId: "claim-pi-1",
    consumerName: "Jordan Reyes",
    consumerAnonymizedId: "Consumer #48213",
    category: "personal_injury",
    subtype: "Motor vehicle accident",
    jurisdiction: "California",
    incidentDate: "2026-05-14",
    submittedAt: "2026-08-02T14:20:00Z",
    status: "new",
    assignedLawyerId: null,
    responseDeadline: "2026-08-06T17:00:00Z",
    matchExplanation: "Matches firm practice area (personal injury), jurisdiction (California), and case type (motor vehicle accident). Evidence profile includes police report and medical records.",
    consumerObjectives: "Recover costs of medical treatment and lost wages; concerned about long-term impact on ability to work.",
    assessment: commonAssessmentPI,
    incidentOverview: "Rear-ended at a red light by another driver who was reportedly distracted. Police and ambulance attended the scene.",
    keyDates: [{ label: "Incident date", date: "2026-05-14" }, { label: "ER treatment", date: "2026-05-14" }, { label: "Began physiotherapy", date: "2026-05-20" }],
    parties: "Consumer (driver); Mark Feldstein (other driver, believed insured via Palisade Mutual Insurance).",
    chronology: "Collision at 4th & Alameda -> ER treatment same day -> physiotherapy started May 20 -> returned to full duties June 2 with ongoing discomfort.",
    injuriesOrConsequences: "Neck and lower back pain, headaches, seatbelt bruising. Ongoing stiffness affecting ability to sit for long periods at work.",
    medicalTreatmentOrWorkplaceResponse: "Treated at Springvale General ER; ongoing physiotherapy twice weekly with Dr. Anita Cole.",
    financialLosses: "6 missed work days plus two weeks of reduced hours as a logistics coordinator.",
    witnesses: "Priya Anand (pedestrian witness), contact information on file.",
    documents: [
      { id: "rd-1", name: "police_report_SVPD-2026-04471.pdf", category: "Police report", description: "Official police report from responding officer.", uploadedAt: "2026-08-02T14:20:00Z" },
      { id: "rd-2", name: "er_discharge_summary.pdf", category: "Medical record", description: "Springvale General ER discharge summary.", uploadedAt: "2026-08-02T14:20:00Z" },
      { id: "rd-3", name: "front_damage_photo.jpg", category: "Photo", description: "Vehicle damage photo.", uploadedAt: "2026-08-02T14:20:00Z" },
    ],
    timeline: [
      { id: "rt-1", date: "2026-05-14", title: "Collision occurs", description: "Rear-ended at a red light.", peopleInvolved: "Jordan Reyes, Mark Feldstein", significance: "high" },
      { id: "rt-2", date: "2026-05-20", title: "Began physiotherapy", description: "Twice-weekly physiotherapy started.", peopleInvolved: "Dr. Anita Cole", significance: "medium" },
    ],
    missingInformation: ["Specialist evaluation of long-term prognosis", "Confirmation of other driver's insurance policy limits"],
    potentialDeadlineConcerns: "California personal injury statute of limitations is approximately 2 years from the incident date (2028-05-14).",
    notes: [],
    conflictCheck: { status: "not_started", entities: [
      { name: "Jordan Reyes", role: "consumer", status: "not_started" },
      { name: "Mark Feldstein", role: "opposing_party", status: "not_started" },
      { name: "Palisade Mutual Insurance", role: "insurer", status: "not_started" },
    ] },
    consultation: null,
    declineReason: null,
    declineDetail: "",
    convertedMatterId: null,
    consentToShare: true,
    lastActivityAt: "2026-08-02T14:20:00Z",
  },
  {
    id: "ref-2",
    source: "JusticeChamp Consumer Intake",
    sourceClaimId: "claim-emp-1",
    consumerName: "Jordan Reyes",
    consumerAnonymizedId: "Consumer #48213",
    category: "employment",
    subtype: "Termination",
    jurisdiction: "California",
    incidentDate: "2026-04-02",
    submittedAt: "2026-08-03T09:10:00Z",
    status: "new",
    assignedLawyerId: null,
    responseDeadline: "2026-08-07T17:00:00Z",
    matchExplanation: "Matches firm practice area (employment) and jurisdiction. Timing between medical leave request, HR complaint, and termination flagged as a potential retaliation pattern.",
    consumerObjectives: "Understand whether the timing of termination relative to a complaint and leave request is legally significant.",
    assessment: commonAssessmentEmp,
    incidentOverview: "Terminated two weeks after filing a formal HR complaint about a manager's comments regarding a medical leave request.",
    keyDates: [{ label: "Medical leave requested", date: "2026-02-10" }, { label: "HR complaint filed", date: "2026-03-10" }, { label: "Placed on PIP", date: "2026-03-18" }, { label: "Terminated", date: "2026-04-02" }],
    parties: "Client (employee); Brightpath Logistics Inc. (employer); A. Whitfield (manager); D. Ostrowski (HR).",
    chronology: "Requested medical leave Feb 10 -> manager comments on reliability -> HR complaint Mar 10 -> PIP Mar 18 -> terminated Apr 2, before 30-day PIP period ended.",
    injuriesOrConsequences: "Lost salary and benefits since termination; significant stress affecting sleep.",
    medicalTreatmentOrWorkplaceResponse: "HR acknowledged the complaint by email but no investigation outcome was shared before termination.",
    financialLosses: "$78,000 base salary plus bonus and benefits since April 2.",
    witnesses: "Coworker T. Nguyen overheard the manager's comments in February.",
    documents: [
      { id: "rd-4", name: "performance_improvement_plan.pdf", category: "Employment record", description: "PIP document dated March 18.", uploadedAt: "2026-08-03T09:10:00Z" },
      { id: "rd-5", name: "termination_letter.pdf", category: "Termination letter", description: "Termination letter dated April 2.", uploadedAt: "2026-08-03T09:10:00Z" },
      { id: "rd-6", name: "hr_complaint_email.pdf", category: "Email", description: "Email thread containing the formal HR complaint.", uploadedAt: "2026-08-03T09:10:00Z" },
    ],
    timeline: [
      { id: "rt-3", date: "2026-03-10", title: "Filed HR complaint", description: "Submitted written complaint about manager's comments.", peopleInvolved: "D. Ostrowski", significance: "high" },
      { id: "rt-4", date: "2026-04-02", title: "Terminated", description: "Terminated via video call before PIP period concluded.", peopleInvolved: "A. Whitfield, D. Ostrowski", significance: "high" },
    ],
    missingInformation: ["Whether any other employees received similar PIPs", "Full copy of the leave approval correspondence"],
    potentialDeadlineConcerns: "Approximate deadline to file an administrative complaint is 2027-04-02 — confirm exact agency filing window at intake.",
    notes: [],
    conflictCheck: { status: "not_started", entities: [
      { name: "Jordan Reyes", role: "consumer", status: "not_started" },
      { name: "Brightpath Logistics Inc.", role: "employer", status: "not_started" },
    ] },
    consultation: null,
    declineReason: null,
    declineDetail: "",
    convertedMatterId: null,
    consentToShare: true,
    lastActivityAt: "2026-08-03T09:10:00Z",
  },
  {
    id: "ref-3",
    source: "JusticeChamp Consumer Intake",
    sourceClaimId: "claim-pi-2",
    consumerName: "Danielle Ortiz",
    consumerAnonymizedId: "Consumer #51092",
    category: "personal_injury",
    subtype: "Slip and fall",
    jurisdiction: "California",
    incidentDate: "2026-06-20",
    submittedAt: "2026-07-28T11:00:00Z",
    status: "more_info_requested",
    assignedLawyerId: "tm-2",
    responseDeadline: "2026-08-05T17:00:00Z",
    matchExplanation: "Matches practice area and jurisdiction; evidence profile is currently thin and additional documentation was requested.",
    consumerObjectives: "Cover medical bills from a fall in a grocery store with no posted wet-floor signage.",
    assessment: { ...commonAssessmentPI, claimReadiness: 46, informationCompleteness: 40, evidenceStrength: 35, documentAvailability: 30, urgency: "moderate" },
    incidentOverview: "Slipped on an unmarked wet floor near a store entrance, resulting in a wrist fracture.",
    keyDates: [{ label: "Incident date", date: "2026-06-20" }],
    parties: "Consumer; Green Valley Grocery (property owner/operator).",
    chronology: "Fall occurred June 20; consumer went to urgent care two days later.",
    injuriesOrConsequences: "Fractured wrist, ongoing pain.",
    medicalTreatmentOrWorkplaceResponse: "Urgent care visit; referral to orthopedic specialist pending.",
    financialLosses: "Not yet documented.",
    witnesses: "Unclear — consumer believes a store employee was nearby.",
    documents: [{ id: "rd-7", name: "urgent_care_note.pdf", category: "Medical record", description: "Urgent care visit summary.", uploadedAt: "2026-07-28T11:00:00Z" }],
    timeline: [{ id: "rt-5", date: "2026-06-20", title: "Fall occurs", description: "Slipped on wet floor near store entrance.", peopleInvolved: "Danielle Ortiz", significance: "high" }],
    missingInformation: ["Incident report from the store, if one exists", "Photos of the location and any signage", "Witness contact information", "Orthopedic specialist records"],
    potentialDeadlineConcerns: "California personal injury statute of limitations approximately 2028-06-20.",
    notes: [{ id: "rn-1", authorId: "tm-2", authorName: "Marcus Delgado", body: "Requested photos of the scene and any incident report from the store manager via the client portal.", createdAt: "2026-07-29T10:00:00Z", visibility: "internal" }],
    conflictCheck: { status: "clear", runAt: "2026-07-29T09:00:00Z", runBy: "Marcus Delgado", entities: [
      { name: "Danielle Ortiz", role: "consumer", status: "clear" },
      { name: "Green Valley Grocery", role: "opposing_party", status: "clear" },
    ] },
    consultation: null,
    declineReason: null,
    declineDetail: "",
    convertedMatterId: null,
    consentToShare: true,
    lastActivityAt: "2026-07-29T10:00:00Z",
  },
  {
    id: "ref-4",
    source: "JusticeChamp Consumer Intake",
    sourceClaimId: "claim-emp-2",
    consumerName: "Michael Osei",
    consumerAnonymizedId: "Consumer #49981",
    category: "employment",
    subtype: "Discrimination",
    jurisdiction: "California",
    incidentDate: "2026-05-02",
    submittedAt: "2026-07-20T13:00:00Z",
    status: "consultation_scheduled",
    assignedLawyerId: "tm-3",
    responseDeadline: "2026-07-24T17:00:00Z",
    matchExplanation: "Matches practice area and jurisdiction; strong documentation of a denied promotion pattern.",
    consumerObjectives: "Understand options after being passed over for promotion three times despite strong reviews.",
    assessment: { ...commonAssessmentEmp, claimReadiness: 81, informationCompleteness: 85 },
    incidentOverview: "Passed over for promotion on three occasions in favor of less-tenured colleagues; believes age was a factor.",
    keyDates: [{ label: "First denial", date: "2025-11-01" }, { label: "Most recent denial", date: "2026-05-02" }],
    parties: "Client; Northgate Financial Services (employer); R. Alvarez (manager).",
    chronology: "Three promotion cycles over 18 months, each resulting in denial with vague feedback.",
    injuriesOrConsequences: "Lost promotion-related salary increases; morale and reputational impact.",
    medicalTreatmentOrWorkplaceResponse: "No formal HR complaint filed yet.",
    financialLosses: "Estimated $22,000/year in foregone salary increase across two cycles.",
    witnesses: "Two coworkers privately shared similar experiences.",
    documents: [{ id: "rd-8", name: "performance_reviews_2024_2026.pdf", category: "Employment record", description: "Three years of performance reviews.", uploadedAt: "2026-07-20T13:00:00Z" }],
    timeline: [{ id: "rt-6", date: "2026-05-02", title: "Third promotion denial", description: "Denied promotion in favor of a less-tenured colleague.", peopleInvolved: "R. Alvarez", significance: "high" }],
    missingInformation: ["Formal HR complaint, if any", "Comparator employee details"],
    potentialDeadlineConcerns: "Administrative filing deadlines vary — confirm at consultation.",
    notes: [{ id: "rn-2", authorId: "tm-3", authorName: "Priya Chandra", body: "Strong documentary record. Scheduling consultation to discuss comparator evidence.", createdAt: "2026-07-21T10:00:00Z", visibility: "internal" }],
    conflictCheck: { status: "clear", runAt: "2026-07-21T09:30:00Z", runBy: "Priya Chandra", entities: [
      { name: "Michael Osei", role: "consumer", status: "clear" },
      { name: "Northgate Financial Services", role: "employer", status: "clear" },
    ] },
    consultation: {
      id: "cons-1", referralId: "ref-4", proposedTimes: ["2026-08-06T16:00:00Z", "2026-08-07T18:00:00Z"], confirmedTime: "2026-08-06T16:00:00Z",
      lawyerId: "tm-3", meetingType: "video", preparationInstructions: "Please have copies of all performance reviews and any written promotion criteria available.",
      status: "confirmed", outcome: undefined, outcomeNotes: "",
    },
    declineReason: null,
    declineDetail: "",
    convertedMatterId: null,
    consentToShare: true,
    lastActivityAt: "2026-07-27T15:00:00Z",
  },
  {
    id: "ref-5",
    source: "JusticeChamp Consumer Intake",
    sourceClaimId: "claim-pi-3",
    consumerName: "Rachel Nakamura",
    consumerAnonymizedId: "Consumer #47765",
    category: "personal_injury",
    subtype: "Product injury",
    jurisdiction: "California",
    incidentDate: "2026-03-11",
    submittedAt: "2026-07-15T10:00:00Z",
    status: "accepted",
    assignedLawyerId: "tm-2",
    responseDeadline: "2026-07-19T17:00:00Z",
    matchExplanation: "Matches practice area and jurisdiction; strong evidence package including product retained as-is and full medical documentation.",
    consumerObjectives: "Pursue compensation after a defective kitchen appliance caused burn injuries.",
    assessment: { ...commonAssessmentPI, claimReadiness: 88, informationCompleteness: 90, evidenceStrength: 85 },
    incidentOverview: "Countertop appliance malfunctioned and caused second-degree burns; product retained unmodified.",
    keyDates: [{ label: "Incident date", date: "2026-03-11" }, { label: "ER treatment", date: "2026-03-11" }, { label: "Follow-up burn clinic", date: "2026-03-25" }],
    parties: "Client; HomeTech Appliances Inc. (manufacturer); Cascade Retail Co. (retailer).",
    chronology: "Malfunction and burn injury March 11 -> ER same day -> burn clinic follow-up March 25 -> product retained for inspection.",
    injuriesOrConsequences: "Second-degree burns to hand and forearm; ongoing scar-management treatment.",
    medicalTreatmentOrWorkplaceResponse: "ER treatment plus ongoing burn clinic follow-up.",
    financialLosses: "Approximately $9,400 in medical costs to date; two weeks off work.",
    witnesses: "Spouse present at time of incident.",
    documents: [
      { id: "rd-9", name: "er_burn_treatment_record.pdf", category: "Medical record", description: "ER burn treatment record.", uploadedAt: "2026-07-15T10:00:00Z" },
      { id: "rd-10", name: "product_photos.zip", category: "Photo", description: "Photos of the malfunctioning appliance.", uploadedAt: "2026-07-15T10:00:00Z" },
    ],
    timeline: [{ id: "rt-7", date: "2026-03-11", title: "Appliance malfunctions", description: "Countertop appliance malfunctioned, causing burns.", peopleInvolved: "Rachel Nakamura", significance: "high" }],
    missingInformation: ["Product model/serial verification", "Any prior recall notices for the product line"],
    potentialDeadlineConcerns: "Product liability statute of limitations approximately 2028-03-11.",
    notes: [
      { id: "rn-3", authorId: "tm-2", authorName: "Marcus Delgado", body: "Consultation completed. Client wants to proceed. Recommend converting to matter this week.", createdAt: "2026-07-30T14:00:00Z", visibility: "internal" },
    ],
    conflictCheck: { status: "clear", runAt: "2026-07-16T09:00:00Z", runBy: "Marcus Delgado", entities: [
      { name: "Rachel Nakamura", role: "consumer", status: "clear" },
      { name: "HomeTech Appliances Inc.", role: "opposing_party", status: "clear" },
      { name: "Cascade Retail Co.", role: "related_organization", status: "clear" },
    ] },
    consultation: {
      id: "cons-2", referralId: "ref-5", proposedTimes: ["2026-07-22T17:00:00Z"], confirmedTime: "2026-07-22T17:00:00Z",
      lawyerId: "tm-2", meetingType: "video", preparationInstructions: "Bring the retained product and all medical bills.",
      status: "completed", outcome: "retained", outcomeNotes: "Client signed engagement letter in principle; ready to formalize as a matter.",
    },
    declineReason: null,
    declineDetail: "",
    convertedMatterId: null,
    consentToShare: true,
    lastActivityAt: "2026-07-30T14:00:00Z",
  },
  {
    id: "ref-6",
    source: "JusticeChamp Consumer Intake",
    sourceClaimId: "claim-emp-3",
    consumerName: "Ben Castellano",
    consumerAnonymizedId: "Consumer #45510",
    category: "employment",
    subtype: "Unpaid wages",
    jurisdiction: "Nevada",
    incidentDate: "2026-06-01",
    submittedAt: "2026-07-10T09:00:00Z",
    status: "declined",
    assignedLawyerId: "tm-3",
    responseDeadline: "2026-07-14T17:00:00Z",
    matchExplanation: "Matched on practice area, but jurisdiction falls outside the firm's licensed states.",
    consumerObjectives: "Recover unpaid overtime wages from a former employer.",
    assessment: { ...commonAssessmentEmp, claimReadiness: 60, urgency: "moderate" },
    incidentOverview: "Alleges unpaid overtime over a six-month period at a Nevada-based employer.",
    keyDates: [{ label: "Incident date", date: "2026-06-01" }],
    parties: "Client; Silver State Logistics (employer).",
    chronology: "Wage dispute identified after reviewing pay stubs against hours worked.",
    injuriesOrConsequences: "Estimated $6,200 in unpaid overtime.",
    medicalTreatmentOrWorkplaceResponse: "Raised informally with a supervisor; no resolution.",
    financialLosses: "$6,200 estimated.",
    witnesses: "None identified.",
    documents: [{ id: "rd-11", name: "pay_stubs.pdf", category: "Pay record", description: "Six months of pay stubs.", uploadedAt: "2026-07-10T09:00:00Z" }],
    timeline: [],
    missingInformation: ["Nevada-licensed counsel referral"],
    potentialDeadlineConcerns: "Nevada wage claim deadlines differ from California — refer out promptly.",
    notes: [{ id: "rn-4", authorId: "tm-3", authorName: "Priya Chandra", body: "Firm is not licensed in Nevada. Declining and will provide a referral resource.", createdAt: "2026-07-11T09:00:00Z", visibility: "internal" }],
    conflictCheck: { status: "not_started", entities: [{ name: "Ben Castellano", role: "consumer", status: "not_started" }] },
    consultation: null,
    declineReason: "Outside jurisdiction",
    declineDetail: "Firm is only licensed to practice in California; referred consumer to a Nevada employment law resource.",
    convertedMatterId: null,
    consentToShare: true,
    lastActivityAt: "2026-07-11T09:00:00Z",
  },
  {
    id: "ref-7",
    source: "JusticeChamp Consumer Intake",
    sourceClaimId: "claim-pi-4",
    consumerName: "Wei Chen",
    consumerAnonymizedId: "Consumer #41230",
    category: "personal_injury",
    subtype: "Motor vehicle accident",
    jurisdiction: "California",
    incidentDate: "2026-01-18",
    submittedAt: "2026-01-25T10:00:00Z",
    status: "converted",
    assignedLawyerId: "tm-2",
    responseDeadline: "2026-01-29T17:00:00Z",
    matchExplanation: "Matches practice area, jurisdiction, and evidence profile.",
    consumerObjectives: "Recover damages after a multi-vehicle highway collision.",
    assessment: { ...commonAssessmentPI, claimReadiness: 91, informationCompleteness: 92, evidenceStrength: 90 },
    incidentOverview: "Multi-vehicle collision on Highway 101 during heavy rain.",
    keyDates: [{ label: "Incident date", date: "2026-01-18" }],
    parties: "Client; two other drivers; California Highway Patrol responded.",
    chronology: "Collision Jan 18 -> hospitalization 3 days -> extensive physical therapy ongoing.",
    injuriesOrConsequences: "Fractured ribs, concussion, ongoing physical therapy.",
    medicalTreatmentOrWorkplaceResponse: "Hospitalized 3 days; ongoing physical therapy twice weekly.",
    financialLosses: "8 weeks off work as a software engineer; $34,000+ in medical costs to date.",
    witnesses: "Two independent witnesses identified by CHP report.",
    documents: [{ id: "rd-12", name: "chp_collision_report.pdf", category: "Police report", description: "CHP collision report.", uploadedAt: "2026-01-25T10:00:00Z" }],
    timeline: [{ id: "rt-8", date: "2026-01-18", title: "Highway collision", description: "Multi-vehicle collision during heavy rain.", peopleInvolved: "Wei Chen and two other drivers", significance: "high" }],
    missingInformation: [],
    potentialDeadlineConcerns: "California personal injury statute of limitations approximately 2028-01-18.",
    notes: [],
    conflictCheck: { status: "clear", runAt: "2026-01-26T09:00:00Z", runBy: "Marcus Delgado", entities: [{ name: "Wei Chen", role: "consumer", status: "clear" }] },
    consultation: { id: "cons-3", referralId: "ref-7", proposedTimes: ["2026-01-28T18:00:00Z"], confirmedTime: "2026-01-28T18:00:00Z", lawyerId: "tm-2", meetingType: "in_person", preparationInstructions: "Bring CHP report and medical records.", status: "completed", outcome: "retained", outcomeNotes: "Retained; converted to matter-1." },
    declineReason: null,
    declineDetail: "",
    convertedMatterId: "matter-1",
    consentToShare: true,
    lastActivityAt: "2026-02-02T11:00:00Z",
  },
  {
    id: "ref-8",
    source: "JusticeChamp Consumer Intake",
    sourceClaimId: "claim-emp-4",
    consumerName: "Latisha Brown",
    consumerAnonymizedId: "Consumer #39984",
    category: "employment",
    subtype: "Retaliation or reprisal",
    jurisdiction: "California",
    incidentDate: "2025-11-05",
    submittedAt: "2025-11-12T10:00:00Z",
    status: "converted",
    assignedLawyerId: "tm-3",
    responseDeadline: "2025-11-16T17:00:00Z",
    matchExplanation: "Matches practice area, jurisdiction, and strong retaliation timeline evidence.",
    consumerObjectives: "Address retaliatory demotion after reporting a safety violation.",
    assessment: { ...commonAssessmentEmp, claimReadiness: 84 },
    incidentOverview: "Demoted two weeks after reporting a workplace safety violation to a supervisor.",
    keyDates: [{ label: "Safety report filed", date: "2025-10-20" }, { label: "Demotion", date: "2025-11-05" }],
    parties: "Client; Meridian Manufacturing (employer).",
    chronology: "Safety report Oct 20 -> demotion Nov 5 with reduced pay and title.",
    injuriesOrConsequences: "Reduced salary and loss of supervisory title.",
    medicalTreatmentOrWorkplaceResponse: "No formal internal investigation conducted.",
    financialLosses: "$14,000/year salary reduction.",
    witnesses: "Two coworkers aware of the safety report.",
    documents: [{ id: "rd-13", name: "safety_report_copy.pdf", category: "Incident report", description: "Copy of the original safety report.", uploadedAt: "2025-11-12T10:00:00Z" }],
    timeline: [{ id: "rt-9", date: "2025-11-05", title: "Demotion", description: "Demoted with reduced pay and title.", peopleInvolved: "Supervisor", significance: "high" }],
    missingInformation: [],
    potentialDeadlineConcerns: "Administrative filing deadline confirmed at intake.",
    notes: [],
    conflictCheck: { status: "clear", runAt: "2025-11-13T09:00:00Z", runBy: "Priya Chandra", entities: [{ name: "Latisha Brown", role: "consumer", status: "clear" }] },
    consultation: { id: "cons-4", referralId: "ref-8", proposedTimes: ["2025-11-15T17:00:00Z"], confirmedTime: "2025-11-15T17:00:00Z", lawyerId: "tm-3", meetingType: "phone", preparationInstructions: "Have safety report and any HR correspondence available.", status: "completed", outcome: "retained", outcomeNotes: "Retained; converted to matter-2." },
    declineReason: null,
    declineDetail: "",
    convertedMatterId: "matter-2",
    consentToShare: true,
    lastActivityAt: "2025-11-20T11:00:00Z",
  },
  {
    id: "ref-9",
    source: "JusticeChamp Consumer Intake",
    sourceClaimId: "claim-pi-5",
    consumerName: "Omar Haddad",
    consumerAnonymizedId: "Consumer #52217",
    category: "personal_injury",
    subtype: "Premises liability",
    jurisdiction: "California",
    incidentDate: "2026-07-01",
    submittedAt: "2026-07-31T16:00:00Z",
    status: "under_review",
    assignedLawyerId: "tm-2",
    responseDeadline: "2026-08-04T17:00:00Z",
    matchExplanation: "Matches practice area and jurisdiction; currently under initial review by assigned lawyer.",
    consumerObjectives: "Understand options after a fall on an unlit stairwell at an apartment complex.",
    assessment: { ...commonAssessmentPI, claimReadiness: 65, urgency: "moderate" },
    incidentOverview: "Fell on an unlit exterior stairwell at an apartment complex, resulting in a knee injury.",
    keyDates: [{ label: "Incident date", date: "2026-07-01" }],
    parties: "Client; Bayview Apartments Management Co.",
    chronology: "Fall occurred at night; consumer sought urgent care the next morning.",
    injuriesOrConsequences: "Knee sprain and bruising.",
    medicalTreatmentOrWorkplaceResponse: "Urgent care visit; no surgery required.",
    financialLosses: "Not yet fully documented.",
    witnesses: "None identified yet.",
    documents: [{ id: "rd-14", name: "stairwell_photo.jpg", category: "Photo", description: "Photo of the unlit stairwell.", uploadedAt: "2026-07-31T16:00:00Z" }],
    timeline: [{ id: "rt-10", date: "2026-07-01", title: "Fall on stairwell", description: "Fell on an unlit exterior stairwell.", peopleInvolved: "Omar Haddad", significance: "high" }],
    missingInformation: ["Maintenance records for stairwell lighting", "Lease agreement"],
    potentialDeadlineConcerns: "California premises liability statute of limitations approximately 2028-07-01.",
    notes: [],
    conflictCheck: { status: "not_started", entities: [{ name: "Omar Haddad", role: "consumer", status: "not_started" }, { name: "Bayview Apartments Management Co.", role: "opposing_party", status: "not_started" }] },
    consultation: null,
    declineReason: null,
    declineDetail: "",
    convertedMatterId: null,
    consentToShare: true,
    lastActivityAt: "2026-08-01T09:00:00Z",
  },
  {
    id: "ref-10",
    source: "JusticeChamp Consumer Intake",
    sourceClaimId: "claim-emp-5",
    consumerName: "Fatima Rahman",
    consumerAnonymizedId: "Consumer #50044",
    category: "employment",
    subtype: "Harassment",
    jurisdiction: "California",
    incidentDate: "2026-06-15",
    submittedAt: "2026-07-25T12:00:00Z",
    status: "conflict",
    assignedLawyerId: "tm-3",
    responseDeadline: "2026-07-29T17:00:00Z",
    matchExplanation: "Matches practice area and jurisdiction; flagged during conflict screening.",
    consumerObjectives: "Address ongoing harassment from a manager at a mid-size retail employer.",
    assessment: { ...commonAssessmentEmp, claimReadiness: 70 },
    incidentOverview: "Reports ongoing harassment from a direct manager over several months.",
    keyDates: [{ label: "Incident date", date: "2026-06-15" }],
    parties: "Client; Meridian Manufacturing (employer).",
    chronology: "Pattern of comments over several months; most recent incident June 15.",
    injuriesOrConsequences: "Emotional distress; considering resignation.",
    medicalTreatmentOrWorkplaceResponse: "No formal complaint filed yet.",
    financialLosses: "Not yet applicable.",
    witnesses: "One coworker witness identified.",
    documents: [],
    timeline: [],
    missingInformation: ["Formal complaint documentation"],
    potentialDeadlineConcerns: "Confirm administrative filing deadline at intake.",
    notes: [{ id: "rn-5", authorId: "tm-3", authorName: "Priya Chandra", body: "Conflict check flagged: firm currently represents Latisha Brown (matter-2) against the same employer, Meridian Manufacturing. Escalating to Managing Partner for review.", createdAt: "2026-07-26T10:00:00Z", visibility: "internal" }],
    conflictCheck: { status: "conflict_confirmed", runAt: "2026-07-26T09:45:00Z", runBy: "Priya Chandra", entities: [
      { name: "Fatima Rahman", role: "consumer", status: "clear" },
      { name: "Meridian Manufacturing", role: "employer", status: "conflict_confirmed" },
    ] },
    consultation: null,
    declineReason: "Conflict",
    declineDetail: "Firm already represents another client in an active matter against the same employer.",
    convertedMatterId: null,
    consentToShare: true,
    lastActivityAt: "2026-07-26T10:00:00Z",
  },
];

// ---------------------------------------------------------------------
// Clients & Contacts
// ---------------------------------------------------------------------

export const CLIENTS: Client[] = [
  { id: "client-1", fullName: "Wei Chen", email: "wei.chen@example.com", phone: "(415) 555-0142", address: "88 Fremont St, San Francisco, CA", relationshipOwnerId: "tm-2", portalStatus: "active", consentHistory: [{ label: "Engagement letter signed", date: "2026-02-03", granted: true }, { label: "Consent to share medical records", date: "2026-02-05", granted: true }] },
  { id: "client-2", fullName: "Latisha Brown", email: "latisha.brown@example.com", phone: "(510) 555-0198", address: "220 Grand Ave, Oakland, CA", relationshipOwnerId: "tm-3", portalStatus: "active", consentHistory: [{ label: "Engagement letter signed", date: "2025-11-22", granted: true }] },
  { id: "client-3", fullName: "Sofia Marquez", email: "sofia.marquez@example.com", phone: "(415) 555-0177", address: "1200 Van Ness Ave, San Francisco, CA", relationshipOwnerId: "tm-2", portalStatus: "active", consentHistory: [{ label: "Engagement letter signed", date: "2025-09-10", granted: true }] },
  { id: "client-4", fullName: "David Okonkwo", email: "david.okonkwo@example.com", phone: "(510) 555-0163", address: "500 Broadway, Oakland, CA", relationshipOwnerId: "tm-3", portalStatus: "invited", consentHistory: [{ label: "Engagement letter signed", date: "2026-04-18", granted: true }] },
  { id: "client-5", fullName: "Grace Liu", email: "grace.liu@example.com", phone: "(415) 555-0121", address: "77 Geary St, San Francisco, CA", relationshipOwnerId: "tm-2", portalStatus: "active", consentHistory: [{ label: "Engagement letter signed", date: "2025-06-01", granted: true }] },
];

export const CONTACTS: Contact[] = [
  { id: "ct-1", name: "Harold Bess", organization: "Bess & Wray Defense Counsel", role: "Opposing counsel", email: "hbess@bwdefense.example", phone: "(415) 555-0301", address: "300 California St, San Francisco, CA", jurisdiction: "California", relatedMatterIds: ["matter-1"], notes: "Represents the other driver's insurer in matter-1.", communicationPreference: "Email" },
  { id: "ct-2", name: "Linda Ferraro", organization: "Palisade Mutual Insurance", role: "Claims adjuster", email: "lferraro@palisademutual.example", phone: "(800) 555-0177", address: "PO Box 4400, Sacramento, CA", jurisdiction: "California", relatedMatterIds: ["matter-1"], notes: "Primary adjuster contact for the collision claim.", communicationPreference: "Phone" },
  { id: "ct-3", name: "Deborah Ostrowski", organization: "Meridian Manufacturing", role: "HR Director", email: "d.ostrowski@meridianmfg.example", phone: "(510) 555-0288", address: "900 Industrial Pkwy, Oakland, CA", jurisdiction: "California", relatedMatterIds: ["matter-2"], notes: "HR point of contact for matter-2 correspondence.", communicationPreference: "Email" },
  { id: "ct-4", name: "Dr. Anita Cole", organization: "Springvale Physiotherapy", role: "Treating provider", email: "acole@springvalept.example", phone: "(415) 555-0199", address: "40 Duboce Ave, San Francisco, CA", jurisdiction: "California", relatedMatterIds: ["matter-3"], notes: "Treating physiotherapist; may be called as a fact witness.", communicationPreference: "Email" },
  { id: "ct-5", name: "James Whitfield, P.E.", organization: "Whitfield Engineering Experts", role: "Retained expert", email: "jwhitfield@whitfieldexperts.example", phone: "(415) 555-0244", address: "12 Battery St, San Francisco, CA", jurisdiction: "California", relatedMatterIds: ["matter-5"], notes: "Retained as a liability reconstruction expert.", communicationPreference: "Email" },
  { id: "ct-6", name: "Karen Mills", organization: "Superior Court of California, Alameda County", role: "Court clerk", email: "kmills@alameda.courts.example", phone: "(510) 555-0100", address: "1225 Fallon St, Oakland, CA", jurisdiction: "California", relatedMatterIds: ["matter-4"], notes: "Departmental clerk contact for filings.", communicationPreference: "Phone" },
];

// ---------------------------------------------------------------------
// Matters
// ---------------------------------------------------------------------

export const MATTERS: Matter[] = [
  {
    id: "matter-1", matterNumber: "PI-2026-0142", sourceReferralId: "ref-7", clientId: "client-1",
    matterName: "Chen v. Palisade Mutual (Highway 101 Collision)", category: "personal_injury", practiceArea: "Personal Injury",
    responsibleLawyerId: "tm-2", teamMemberIds: ["tm-2", "tm-5"], stage: "Discovery", status: "active",
    openDate: "2026-02-03", nextDeadline: "2026-08-15", nextDeadlineLabel: "Deadline to respond to written discovery requests",
    lastActivityAt: "2026-08-01T14:00:00Z", riskStatus: "on_track",
    caseGoals: "Secure fair compensation for medical costs, lost wages, and pain and suffering.",
    nextRecommendedAction: "Finalize responses to defendant's written discovery requests before the August 15 deadline.",
    retainerStatus: "signed", consentStatus: "granted", clientPortalStatus: "active", jurisdiction: "California",
    parties: [
      { id: "mp-1", name: "Wei Chen", role: "client", contactInfo: "wei.chen@example.com" },
      { id: "mp-2", name: "Mark Feldstein", role: "opposing_party", contactInfo: "Represented by Bess & Wray Defense Counsel" },
      { id: "mp-3", name: "Palisade Mutual Insurance", role: "insurer", contactInfo: "Linda Ferraro, adjuster" },
      { id: "mp-4", name: "Harold Bess", role: "defence_lawyer", contactInfo: "hbess@bwdefense.example" },
    ],
    timeline: [
      { id: "mt-1", date: "2026-01-18", title: "Collision occurs", description: "Multi-vehicle collision on Highway 101.", peopleInvolved: "Wei Chen", significance: "high" },
      { id: "mt-2", date: "2026-02-03", title: "Matter opened", description: "Engagement letter signed; matter formally opened.", peopleInvolved: "Marcus Delgado", significance: "medium" },
      { id: "mt-3", date: "2026-05-10", title: "Demand letter sent", description: "Initial demand letter sent to Palisade Mutual.", peopleInvolved: "Marcus Delgado", significance: "high" },
      { id: "mt-4", date: "2026-07-02", title: "Complaint filed", description: "Complaint filed after demand was undervalued.", peopleInvolved: "Marcus Delgado", significance: "high" },
    ],
    documents: [
      { id: "md-1", name: "chp_collision_report.pdf", folder: "Intake", category: "Police report", uploadedBy: "Emily Tran", uploadedAt: "2026-02-03T10:00:00Z", confidentiality: "standard", clientVisible: true, tags: ["police", "liability"], sizeLabel: "612 KB" },
      { id: "md-2", name: "medical_records_bundle.pdf", folder: "Medical", category: "Medical record", uploadedBy: "Emily Tran", uploadedAt: "2026-03-01T10:00:00Z", confidentiality: "confidential", clientVisible: true, tags: ["medical"], sizeLabel: "4.2 MB" },
      { id: "md-3", name: "demand_letter_draft.docx", folder: "Correspondence", category: "Correspondence", uploadedBy: "Marcus Delgado", uploadedAt: "2026-05-08T10:00:00Z", confidentiality: "privileged", clientVisible: false, tags: ["demand"], sizeLabel: "88 KB" },
      { id: "md-4", name: "discovery_requests_defendant.pdf", folder: "Discovery", category: "Discovery", uploadedBy: "Marcus Delgado", uploadedAt: "2026-07-20T10:00:00Z", confidentiality: "standard", clientVisible: false, tags: ["discovery"], sizeLabel: "310 KB" },
    ],
    notes: [{ id: "mn-1", authorName: "Marcus Delgado", body: "Client's physical therapy progress is positive; will strengthen damages narrative for demand revision.", createdAt: "2026-07-15T11:00:00Z" }],
    damages: [
      { id: "dmg-1", category: "Medical expenses", description: "ER, hospitalization, physical therapy to date", amount: 34500 },
      { id: "dmg-2", category: "Lost income", description: "8 weeks off work, software engineer salary", amount: 12800 },
      { id: "dmg-3", category: "Future care", description: "Estimated ongoing physical therapy, 6 months", amount: 6000 },
    ],
  },
  {
    id: "matter-2", matterNumber: "EMP-2025-0088", sourceReferralId: "ref-8", clientId: "client-2",
    matterName: "Brown v. Meridian Manufacturing (Retaliatory Demotion)", category: "employment", practiceArea: "Employment Law",
    responsibleLawyerId: "tm-3", teamMemberIds: ["tm-3", "tm-5"], stage: "Demand or Negotiation", status: "active",
    openDate: "2025-11-20", nextDeadline: "2026-08-10", nextDeadlineLabel: "Employer response to demand letter due",
    lastActivityAt: "2026-07-28T09:00:00Z", riskStatus: "attention",
    caseGoals: "Reinstate title and pay, or negotiate a fair separation and back-pay settlement.",
    nextRecommendedAction: "Follow up with employer's counsel if no response is received by August 10.",
    retainerStatus: "signed", consentStatus: "granted", clientPortalStatus: "active", jurisdiction: "California",
    parties: [
      { id: "mp-5", name: "Latisha Brown", role: "client", contactInfo: "latisha.brown@example.com" },
      { id: "mp-6", name: "Meridian Manufacturing", role: "employer", contactInfo: "Deborah Ostrowski, HR Director" },
    ],
    timeline: [
      { id: "mt-5", date: "2025-10-20", title: "Safety report filed", description: "Client reported a safety violation to a supervisor.", peopleInvolved: "Latisha Brown", significance: "high" },
      { id: "mt-6", date: "2025-11-05", title: "Demotion", description: "Client demoted with reduced pay and title.", peopleInvolved: "Supervisor", significance: "high" },
      { id: "mt-7", date: "2025-11-20", title: "Matter opened", description: "Engagement letter signed.", peopleInvolved: "Priya Chandra", significance: "medium" },
      { id: "mt-8", date: "2026-06-15", title: "Demand letter sent", description: "Demand letter sent to Meridian Manufacturing counsel.", peopleInvolved: "Priya Chandra", significance: "high" },
    ],
    documents: [
      { id: "md-5", name: "safety_report_copy.pdf", folder: "Intake", category: "Incident report", uploadedBy: "Emily Tran", uploadedAt: "2025-11-20T10:00:00Z", confidentiality: "standard", clientVisible: true, tags: ["safety"], sizeLabel: "144 KB" },
      { id: "md-6", name: "demotion_memo.pdf", folder: "Employment Records", category: "Employment record", uploadedBy: "Emily Tran", uploadedAt: "2025-11-21T10:00:00Z", confidentiality: "standard", clientVisible: true, tags: ["demotion"], sizeLabel: "96 KB" },
      { id: "md-7", name: "demand_letter_sent.pdf", folder: "Correspondence", category: "Correspondence", uploadedBy: "Priya Chandra", uploadedAt: "2026-06-15T10:00:00Z", confidentiality: "privileged", clientVisible: false, tags: ["demand"], sizeLabel: "112 KB" },
    ],
    notes: [{ id: "mn-2", authorName: "Priya Chandra", body: "No response yet from employer's counsel; plan to follow up by phone this week if silence continues.", createdAt: "2026-07-28T09:00:00Z" }],
    damages: [
      { id: "dmg-4", category: "Salary loss", description: "Annualized salary reduction since demotion", amount: 14000 },
      { id: "dmg-5", category: "Benefits loss", description: "Reduced 401k match tied to salary band", amount: 1200 },
    ],
  },
  {
    id: "matter-3", matterNumber: "PI-2025-0301", sourceReferralId: null, clientId: "client-3",
    matterName: "Marquez v. Green Valley Grocery (Slip and Fall)", category: "personal_injury", practiceArea: "Personal Injury",
    responsibleLawyerId: "tm-2", teamMemberIds: ["tm-2"], stage: "Mediation", status: "active",
    openDate: "2025-09-15", nextDeadline: "2026-08-20", nextDeadlineLabel: "Mediation session",
    lastActivityAt: "2026-07-25T13:00:00Z", riskStatus: "on_track",
    caseGoals: "Resolve claim through mediation without proceeding to trial.",
    nextRecommendedAction: "Finalize mediation brief and settlement range with client before August 20.",
    retainerStatus: "signed", consentStatus: "granted", clientPortalStatus: "active", jurisdiction: "California",
    parties: [
      { id: "mp-7", name: "Sofia Marquez", role: "client", contactInfo: "sofia.marquez@example.com" },
      { id: "mp-8", name: "Green Valley Grocery", role: "opposing_party", contactInfo: "Represented by outside counsel" },
      { id: "mp-9", name: "Dr. Anita Cole", role: "medical_provider", contactInfo: "acole@springvalept.example" },
    ],
    timeline: [
      { id: "mt-9", date: "2025-08-02", title: "Fall occurs", description: "Slip and fall near store entrance.", peopleInvolved: "Sofia Marquez", significance: "high" },
      { id: "mt-10", date: "2025-09-15", title: "Matter opened", description: "Engagement letter signed.", peopleInvolved: "Marcus Delgado", significance: "medium" },
      { id: "mt-11", date: "2026-03-01", title: "Complaint filed", description: "Complaint filed after informal negotiation stalled.", peopleInvolved: "Marcus Delgado", significance: "high" },
      { id: "mt-12", date: "2026-06-10", title: "Mediation scheduled", description: "Mediation session scheduled for August 20.", peopleInvolved: "Marcus Delgado", significance: "medium" },
    ],
    documents: [
      { id: "md-8", name: "incident_report_store.pdf", folder: "Intake", category: "Incident report", uploadedBy: "Emily Tran", uploadedAt: "2025-09-15T10:00:00Z", confidentiality: "standard", clientVisible: true, tags: ["liability"], sizeLabel: "204 KB" },
      { id: "md-9", name: "mediation_brief_draft.docx", folder: "Internal Work Product", category: "Work product", uploadedBy: "Marcus Delgado", uploadedAt: "2026-07-20T10:00:00Z", confidentiality: "privileged", clientVisible: false, tags: ["mediation"], sizeLabel: "156 KB" },
    ],
    notes: [{ id: "mn-3", authorName: "Marcus Delgado", body: "Client comfortable with settlement range discussed; proceeding to finalize mediation brief.", createdAt: "2026-07-25T13:00:00Z" }],
    damages: [
      { id: "dmg-6", category: "Medical expenses", description: "Wrist fracture treatment and physical therapy", amount: 18200 },
      { id: "dmg-7", category: "Lost income", description: "3 weeks off work", amount: 4100 },
    ],
  },
  {
    id: "matter-4", matterNumber: "EMP-2026-0055", sourceReferralId: null, clientId: "client-4",
    matterName: "Okonkwo v. Northgate Financial Services (Wrongful Termination)", category: "employment", practiceArea: "Employment Law",
    responsibleLawyerId: "tm-3", teamMemberIds: ["tm-3", "tm-4"], stage: "Pleadings", status: "active",
    openDate: "2026-04-20", nextDeadline: "2026-08-12", nextDeadlineLabel: "Answer to complaint due from defendant",
    lastActivityAt: "2026-07-29T15:00:00Z", riskStatus: "attention",
    caseGoals: "Establish wrongful termination and recover lost wages and reputational damages.",
    nextRecommendedAction: "Monitor for defendant's answer; prepare initial discovery requests in the meantime.",
    retainerStatus: "signed", consentStatus: "granted", clientPortalStatus: "invited", jurisdiction: "California",
    parties: [
      { id: "mp-10", name: "David Okonkwo", role: "client", contactInfo: "david.okonkwo@example.com" },
      { id: "mp-11", name: "Northgate Financial Services", role: "employer", contactInfo: "HR department" },
    ],
    timeline: [
      { id: "mt-13", date: "2026-02-14", title: "Termination", description: "Terminated following a disputed performance review cycle.", peopleInvolved: "David Okonkwo", significance: "high" },
      { id: "mt-14", date: "2026-04-20", title: "Matter opened", description: "Engagement letter signed.", peopleInvolved: "Priya Chandra", significance: "medium" },
      { id: "mt-15", date: "2026-07-15", title: "Complaint filed", description: "Complaint filed in Alameda County Superior Court.", peopleInvolved: "Priya Chandra", significance: "high" },
    ],
    documents: [
      { id: "md-10", name: "termination_letter.pdf", folder: "Employment Records", category: "Termination letter", uploadedBy: "Emily Tran", uploadedAt: "2026-04-20T10:00:00Z", confidentiality: "standard", clientVisible: true, tags: ["termination"], sizeLabel: "98 KB" },
      { id: "md-11", name: "complaint_filed.pdf", folder: "Pleadings", category: "Pleading", uploadedBy: "Priya Chandra", uploadedAt: "2026-07-15T10:00:00Z", confidentiality: "standard", clientVisible: true, tags: ["pleadings"], sizeLabel: "220 KB" },
    ],
    notes: [{ id: "mn-4", authorName: "Priya Chandra", body: "Filed complaint on schedule; awaiting proof of service confirmation.", createdAt: "2026-07-29T15:00:00Z" }],
    damages: [
      { id: "dmg-8", category: "Salary loss", description: "6 months unemployed following termination", amount: 41000 },
      { id: "dmg-9", category: "Mitigation income", description: "Part-time consulting income earned during job search", amount: -6000 },
    ],
  },
  {
    id: "matter-5", matterNumber: "PI-2025-0119", sourceReferralId: null, clientId: "client-5",
    matterName: "Liu v. Cascade Rideshare (Rideshare Collision)", category: "personal_injury", practiceArea: "Personal Injury",
    responsibleLawyerId: "tm-2", teamMemberIds: ["tm-2", "tm-5"], stage: "Pre-Trial", status: "active",
    openDate: "2025-06-10", nextDeadline: "2026-09-02", nextDeadlineLabel: "Pre-trial conference",
    lastActivityAt: "2026-07-18T10:00:00Z", riskStatus: "at_risk",
    caseGoals: "Proceed to trial if a fair pre-trial settlement is not reached.",
    nextRecommendedAction: "Finalize expert witness report ahead of the pre-trial conference.",
    retainerStatus: "signed", consentStatus: "granted", clientPortalStatus: "active", jurisdiction: "California",
    parties: [
      { id: "mp-12", name: "Grace Liu", role: "client", contactInfo: "grace.liu@example.com" },
      { id: "mp-13", name: "Cascade Rideshare Inc.", role: "opposing_party", contactInfo: "Represented by outside counsel" },
      { id: "mp-14", name: "James Whitfield, P.E.", role: "expert", contactInfo: "jwhitfield@whitfieldexperts.example" },
    ],
    timeline: [
      { id: "mt-16", date: "2025-04-02", title: "Collision occurs", description: "Rideshare vehicle collision.", peopleInvolved: "Grace Liu", significance: "high" },
      { id: "mt-17", date: "2025-06-10", title: "Matter opened", description: "Engagement letter signed.", peopleInvolved: "Marcus Delgado", significance: "medium" },
      { id: "mt-18", date: "2025-12-01", title: "Complaint filed", description: "Complaint filed against rideshare company.", peopleInvolved: "Marcus Delgado", significance: "high" },
      { id: "mt-19", date: "2026-05-01", title: "Discovery closed", description: "Fact discovery period closed.", peopleInvolved: "Marcus Delgado", significance: "medium" },
    ],
    documents: [
      { id: "md-12", name: "expert_report_draft.pdf", folder: "Expert Reports", category: "Expert report", uploadedBy: "James Whitfield", uploadedAt: "2026-07-10T10:00:00Z", confidentiality: "privileged", clientVisible: false, tags: ["expert"], sizeLabel: "1.1 MB" },
      { id: "md-13", name: "deposition_transcript_defendant.pdf", folder: "Discovery", category: "Discovery", uploadedBy: "Marcus Delgado", uploadedAt: "2026-06-01T10:00:00Z", confidentiality: "confidential", clientVisible: false, tags: ["deposition"], sizeLabel: "2.4 MB" },
    ],
    notes: [{ id: "mn-5", authorName: "Marcus Delgado", body: "Expert report is running slightly behind schedule; following up with Whitfield Engineering this week.", createdAt: "2026-07-18T10:00:00Z" }],
    damages: [
      { id: "dmg-10", category: "Medical expenses", description: "Surgery and ongoing rehabilitation", amount: 88000 },
      { id: "dmg-11", category: "Lost income", description: "4 months off work", amount: 22000 },
      { id: "dmg-12", category: "Future care", description: "Estimated future rehabilitation needs", amount: 15000 },
    ],
  },
];

// ---------------------------------------------------------------------
// Tasks
// ---------------------------------------------------------------------

export const TASKS: MatterTask[] = [
  { id: "task-1", matterId: "matter-1", title: "Respond to defendant's written discovery requests", assigneeId: "tm-2", dueDate: "2026-08-15", priority: "high", status: "in_progress", description: "Draft and finalize responses to interrogatories and requests for production.", checklist: [{ label: "Draft responses", done: true }, { label: "Client review", done: false }, { label: "Serve responses", done: false }], createdBy: "Marcus Delgado" },
  { id: "task-2", matterId: "matter-1", title: "Order updated medical records", assigneeId: "tm-5", dueDate: "2026-08-01", priority: "normal", status: "waiting", description: "Request the most recent physical therapy progress notes.", checklist: [{ label: "Send records request", done: true }, { label: "Follow up if no response in 10 days", done: false }], createdBy: "Marcus Delgado" },
  { id: "task-3", matterId: "matter-2", title: "Follow up with employer's counsel on demand letter", assigneeId: "tm-3", dueDate: "2026-08-01", priority: "urgent", status: "not_started", description: "No response received to the June 15 demand letter; follow up by phone and email.", checklist: [], createdBy: "Priya Chandra" },
  { id: "task-4", matterId: "matter-2", title: "Prepare back-pay calculation exhibit", assigneeId: "tm-5", dueDate: "2026-08-08", priority: "normal", status: "in_progress", description: "Calculate total back pay and benefits loss since demotion.", checklist: [{ label: "Gather pay stubs", done: true }, { label: "Calculate totals", done: false }], createdBy: "Priya Chandra" },
  { id: "task-5", matterId: "matter-3", title: "Finalize mediation brief", assigneeId: "tm-2", dueDate: "2026-08-14", priority: "high", status: "in_progress", description: "Complete the mediation brief ahead of the August 20 session.", checklist: [{ label: "Draft brief", done: true }, { label: "Client sign-off", done: false }], createdBy: "Marcus Delgado" },
  { id: "task-6", matterId: "matter-3", title: "Confirm mediator availability", assigneeId: "tm-5", dueDate: "2026-07-30", priority: "normal", status: "complete", description: "Confirm mediator and venue for August 20.", checklist: [], createdBy: "Marcus Delgado", completionDate: "2026-07-28" },
  { id: "task-7", matterId: "matter-4", title: "Monitor for defendant's answer", assigneeId: "tm-3", dueDate: "2026-08-12", priority: "normal", status: "waiting", description: "Track court docket for defendant's answer to the complaint.", checklist: [], createdBy: "Priya Chandra" },
  { id: "task-8", matterId: "matter-4", title: "Draft initial discovery requests", assigneeId: "tm-4", dueDate: "2026-08-20", priority: "normal", status: "not_started", description: "Prepare first set of interrogatories and document requests.", checklist: [], createdBy: "Priya Chandra" },
  { id: "task-9", matterId: "matter-5", title: "Follow up with expert on report timeline", assigneeId: "tm-2", dueDate: "2026-07-25", priority: "urgent", status: "in_progress", description: "Expert report is behind schedule ahead of the pre-trial conference.", checklist: [], createdBy: "Marcus Delgado" },
  { id: "task-10", matterId: "matter-5", title: "Prepare pre-trial conference statement", assigneeId: "tm-2", dueDate: "2026-08-25", priority: "high", status: "not_started", description: "Draft the joint pre-trial conference statement.", checklist: [], createdBy: "Marcus Delgado" },
  { id: "task-11", matterId: "matter-1", title: "Schedule client check-in call", assigneeId: "tm-5", dueDate: "2026-08-05", priority: "low", status: "not_started", description: "Routine monthly check-in with client on case status.", checklist: [], createdBy: "Marcus Delgado" },
  { id: "task-12", matterId: "matter-2", title: "Update client on negotiation status", assigneeId: "tm-3", dueDate: "2026-07-29", priority: "normal", status: "complete", description: "Send client a status update summarizing the demand letter and next steps.", checklist: [], createdBy: "Priya Chandra", completionDate: "2026-07-28" },
];

// ---------------------------------------------------------------------
// Calendar events
// ---------------------------------------------------------------------

export const CALENDAR_EVENTS: CalendarEvent[] = [
  { id: "cal-1", matterId: null, referralId: "ref-4", title: "Consultation — Michael Osei", type: "consultation", date: "2026-08-06", time: "09:00", lawyerId: "tm-3", description: "Video consultation regarding promotion denial pattern." },
  { id: "cal-2", matterId: "matter-1", referralId: null, title: "Discovery response deadline", type: "filing_deadline", date: "2026-08-15", time: "17:00", lawyerId: "tm-2", description: "Deadline to serve responses to written discovery." },
  { id: "cal-3", matterId: "matter-2", referralId: null, title: "Employer response deadline", type: "follow_up", date: "2026-08-10", time: "17:00", lawyerId: "tm-3", description: "Follow up if no employer response to demand letter." },
  { id: "cal-4", matterId: "matter-3", referralId: null, title: "Mediation session", type: "mediation", date: "2026-08-20", time: "10:00", lawyerId: "tm-2", description: "Mediation session at JAMS San Francisco." },
  { id: "cal-5", matterId: "matter-4", referralId: null, title: "Defendant answer due", type: "court_deadline", date: "2026-08-12", time: "17:00", lawyerId: "tm-3", description: "Defendant's answer to the complaint is due." },
  { id: "cal-6", matterId: "matter-5", referralId: null, title: "Pre-trial conference", type: "hearing", date: "2026-09-02", time: "09:30", lawyerId: "tm-2", description: "Pre-trial conference at Alameda County Superior Court." },
  { id: "cal-7", matterId: "matter-1", referralId: null, title: "Client check-in call", type: "client_meeting", date: "2026-08-05", time: "14:00", lawyerId: "tm-5", description: "Monthly status check-in with Wei Chen." },
  { id: "cal-8", matterId: "matter-5", referralId: null, title: "Expert report internal review", type: "internal_review", date: "2026-08-08", time: "11:00", lawyerId: "tm-2", description: "Internal review of the expert engineering report draft." },
  { id: "cal-9", matterId: null, referralId: "ref-9", title: "Internal review — Omar Haddad referral", type: "internal_review", date: "2026-08-04", time: "16:00", lawyerId: "tm-2", description: "Review premises liability referral before response deadline." },
  { id: "cal-10", matterId: "matter-3", referralId: null, title: "Sofia Marquez physical therapy follow-up", type: "medical_appointment", date: "2026-08-11", time: "10:30", lawyerId: "tm-2", description: "Client's ongoing physical therapy appointment (tracked for damages documentation)." },
  { id: "cal-11", matterId: "matter-4", referralId: null, title: "Discovery planning meeting", type: "discovery", date: "2026-08-18", time: "13:00", lawyerId: "tm-3", description: "Internal discovery strategy meeting." },
  { id: "cal-12", matterId: "matter-2", referralId: null, title: "California employment filing deadline", type: "limitation_period", date: "2027-04-02", time: "17:00", lawyerId: "tm-3", description: "Outer administrative filing deadline to calendar and verify independently." },
];

// ---------------------------------------------------------------------
// Communications
// ---------------------------------------------------------------------

export const COMMUNICATIONS: Communication[] = [
  { id: "comm-1", matterId: "matter-1", referralId: null, clientId: "client-1", type: "secure_message", from: "Marcus Delgado", to: "Wei Chen", subject: "Discovery update", body: "We've received the defendant's written discovery requests and are preparing responses ahead of the August 15 deadline.", createdAt: "2026-08-01T14:00:00Z", teamMemberId: "tm-2" },
  { id: "comm-2", matterId: "matter-1", referralId: null, clientId: "client-1", type: "document_request", from: "Emily Tran", to: "Wei Chen", subject: "Updated physical therapy records", body: "Could you ask Springvale Physiotherapy to send us your most recent progress notes?", createdAt: "2026-07-20T10:00:00Z", teamMemberId: "tm-5" },
  { id: "comm-3", matterId: "matter-2", referralId: null, clientId: "client-2", type: "secure_message", from: "Priya Chandra", to: "Latisha Brown", subject: "Demand letter sent", body: "We've sent the demand letter to Meridian Manufacturing's counsel. We'll follow up if we don't hear back within a few weeks.", createdAt: "2026-06-15T15:00:00Z", teamMemberId: "tm-3" },
  { id: "comm-4", matterId: null, referralId: "ref-1", clientId: null, type: "automated_reminder", from: "JusticeIQ System", to: "Marcus Delgado", subject: "New referral awaiting review", body: "A new personal injury referral from JusticeChamp Consumer Intake is awaiting review. Response deadline: Aug 6, 2026.", createdAt: "2026-08-02T14:25:00Z", teamMemberId: "tm-2" },
  { id: "comm-5", matterId: null, referralId: "ref-3", clientId: null, type: "document_request", from: "Marcus Delgado", to: "Danielle Ortiz", subject: "Additional documentation requested", body: "To continue evaluating your claim, could you share any photos of the location and confirm whether a store employee witnessed the fall?", createdAt: "2026-07-29T10:00:00Z", teamMemberId: "tm-2" },
  { id: "comm-6", matterId: null, referralId: "ref-4", clientId: null, type: "consultation_note", from: "Priya Chandra", to: "Internal", subject: "Pre-consultation prep notes", body: "Reviewed performance reviews; documentary record is strong. Plan to explore comparator evidence during the consultation.", createdAt: "2026-07-27T15:00:00Z", teamMemberId: "tm-3" },
  { id: "comm-7", matterId: "matter-3", referralId: null, clientId: "client-3", type: "phone_note", from: "Marcus Delgado", to: "Sofia Marquez", subject: "Settlement range discussion", body: "Called client to discuss acceptable settlement range ahead of mediation. Client comfortable with the proposed range.", createdAt: "2026-07-25T13:00:00Z", teamMemberId: "tm-2" },
  { id: "comm-8", matterId: "matter-4", referralId: null, clientId: "client-4", type: "email_log", from: "Priya Chandra", to: "David Okonkwo", subject: "Complaint filed confirmation", body: "Confirming that we filed the complaint on July 15. We're now awaiting the defendant's response.", createdAt: "2026-07-15T16:00:00Z", teamMemberId: "tm-3" },
  { id: "comm-9", matterId: "matter-5", referralId: null, clientId: "client-5", type: "internal_comment", from: "Marcus Delgado", to: "Internal", subject: "Expert report timeline", body: "Following up with Whitfield Engineering — report is running about a week behind schedule.", createdAt: "2026-07-18T10:00:00Z", teamMemberId: "tm-2" },
  { id: "comm-10", matterId: null, referralId: "ref-6", clientId: null, type: "email_log", from: "Priya Chandra", to: "Ben Castellano", subject: "Referral declined — outside jurisdiction", body: "Thank you for reaching out. Our firm is only licensed in California, so we're unable to represent you in this Nevada wage matter. We've included a referral resource below.", createdAt: "2026-07-11T09:15:00Z", teamMemberId: "tm-3" },
  { id: "comm-11", matterId: "matter-2", referralId: null, clientId: "client-2", type: "automated_reminder", from: "JusticeIQ System", to: "Priya Chandra", subject: "Deadline approaching", body: "Employer response to the demand letter is due within 2 weeks (Aug 10, 2026).", createdAt: "2026-07-27T08:00:00Z", teamMemberId: "tm-3" },
  { id: "comm-12", matterId: null, referralId: "ref-9", clientId: null, type: "internal_comment", from: "Marcus Delgado", to: "Internal", subject: "Initial review notes", body: "Reviewing premises liability referral; requesting maintenance and lease records before scheduling a consultation.", createdAt: "2026-08-01T09:00:00Z", teamMemberId: "tm-2" },
];

// ---------------------------------------------------------------------
// Case changes & client updates (JusticeIQ -> JusticeChamp bridge)
// ---------------------------------------------------------------------

export const CASE_CHANGES: CaseChangeEntry[] = [
  {
    id: "cc-1",
    matterId: "matter-1",
    summary: "Defendant's insurer provided additional documents",
    detail: "Received Palisade Mutual's supplemental claim file, including the adjuster's inspection photos and a revised damage estimate.",
    category: "documents",
    internalOnly: false,
    createdBy: "Marcus Delgado",
    createdAt: "2026-08-05T16:10:00Z",
    clientUpdateId: "cu-1",
  },
];

export const CLIENT_UPDATES: ClientUpdate[] = [
  {
    id: "cu-1",
    matterId: "matter-1",
    clientId: "client-1",
    caseChangeIds: ["cc-1"],
    subject: "Case Update",
    message:
      "There has been an update to your case.\n\nThe defendant has provided additional documents and your lawyer has updated your file to reflect this new information.\n\nNo action is required from you at this time.\n\nYour legal team will continue reviewing the information and will contact you if anything further is required.",
    sendingLawyer: "Marcus Delgado",
    sentAt: "2026-08-05T16:14:00Z",
    deliveryStatus: "sent",
  },
];

// ---------------------------------------------------------------------
// Notifications & activity log
// ---------------------------------------------------------------------

export const NOTIFICATIONS: Notification[] = [
  { id: "not-1", message: "New personal injury referral from JusticeChamp — Jordan Reyes (motor vehicle accident).", type: "referral", createdAt: "2026-08-02T14:20:00Z", read: false },
  { id: "not-2", message: "New employment referral from JusticeChamp — Jordan Reyes (termination).", type: "referral", createdAt: "2026-08-03T09:10:00Z", read: false },
  { id: "not-3", message: "Discovery response deadline for Chen matter is in 2 weeks.", type: "deadline", createdAt: "2026-08-01T08:00:00Z", read: false },
  { id: "not-4", message: "Task overdue: Follow up with employer's counsel (Brown matter).", type: "task", createdAt: "2026-08-02T08:00:00Z", read: false },
  { id: "not-5", message: "New secure message from Wei Chen.", type: "message", createdAt: "2026-08-01T14:05:00Z", read: true },
  { id: "not-6", message: "Consultation confirmed with Michael Osei for Aug 6.", type: "referral", createdAt: "2026-07-27T15:05:00Z", read: true },
];

export const ACTIVITY_LOG: ActivityLogItem[] = [
  { id: "act-1", message: "Received new referral ref-1 (Jordan Reyes, personal injury) from JusticeChamp.", timestamp: "2026-08-02T14:20:00Z", actor: "JusticeIQ System" },
  { id: "act-2", message: "Received new referral ref-2 (Jordan Reyes, employment) from JusticeChamp.", timestamp: "2026-08-03T09:10:00Z", actor: "JusticeIQ System" },
  { id: "act-3", message: "Requested additional documentation on referral ref-3 (Danielle Ortiz).", timestamp: "2026-07-29T10:00:00Z", actor: "Marcus Delgado" },
  { id: "act-4", message: "Confirmed consultation for referral ref-4 (Michael Osei).", timestamp: "2026-07-27T15:00:00Z", actor: "Priya Chandra" },
  { id: "act-5", message: "Marked referral ref-5 (Rachel Nakamura) as accepted.", timestamp: "2026-07-30T14:00:00Z", actor: "Marcus Delgado" },
  { id: "act-6", message: "Declined referral ref-6 (Ben Castellano) — outside jurisdiction.", timestamp: "2026-07-11T09:00:00Z", actor: "Priya Chandra" },
  { id: "act-7", message: "Converted referral ref-7 to matter-1 (Chen v. Palisade Mutual).", timestamp: "2026-02-02T11:00:00Z", actor: "Marcus Delgado" },
  { id: "act-8", message: "Converted referral ref-8 to matter-2 (Brown v. Meridian Manufacturing).", timestamp: "2025-11-20T11:00:00Z", actor: "Priya Chandra" },
  { id: "act-9", message: "Conflict confirmed on referral ref-10 (Fatima Rahman) — existing matter against same employer.", timestamp: "2026-07-26T10:00:00Z", actor: "Priya Chandra" },
  { id: "act-10", message: "Filed complaint in matter-4 (Okonkwo v. Northgate Financial Services).", timestamp: "2026-07-15T10:00:00Z", actor: "Priya Chandra" },
];

// ---------------------------------------------------------------------
// Subscription tiers
// ---------------------------------------------------------------------

export const SUBSCRIPTION_TIERS: SubscriptionTier[] = [
  { id: "basic", name: "Basic", monthlyPrice: 0, users: "Up to 2", referrals: "5 / month", activeMatters: "10", storage: "5 GB", aiAssistance: false, workflowAutomation: false, advancedReporting: false, integrations: false, support: "Community + email", multiOffice: false, customIntakeCriteria: false, businessIntelligence: false },
  { id: "bronze", name: "Bronze", monthlyPrice: 149, users: "Up to 5", referrals: "20 / month", activeMatters: "40", storage: "25 GB", aiAssistance: false, workflowAutomation: true, advancedReporting: false, integrations: false, support: "Email, 1 business day", multiOffice: false, customIntakeCriteria: true, businessIntelligence: false },
  { id: "silver", name: "Silver", monthlyPrice: 349, users: "Up to 15", referrals: "60 / month", activeMatters: "150", storage: "100 GB", aiAssistance: true, workflowAutomation: true, advancedReporting: true, integrations: true, support: "Priority email + chat", multiOffice: false, customIntakeCriteria: true, businessIntelligence: false },
  { id: "gold", name: "Gold", monthlyPrice: 749, users: "Up to 40", referrals: "150 / month", activeMatters: "400", storage: "500 GB", aiAssistance: true, workflowAutomation: true, advancedReporting: true, integrations: true, support: "Priority phone + chat", multiOffice: true, customIntakeCriteria: true, businessIntelligence: true },
  { id: "platinum", name: "Platinum", monthlyPrice: 1499, users: "Unlimited", referrals: "Unlimited", activeMatters: "Unlimited", storage: "2 TB", aiAssistance: true, workflowAutomation: true, advancedReporting: true, integrations: true, support: "Dedicated account manager", multiOffice: true, customIntakeCriteria: true, businessIntelligence: true },
];

// ---------------------------------------------------------------------
// Task templates
// ---------------------------------------------------------------------

export const TASK_TEMPLATES: TaskTemplateItem[] = [
  { id: "tpl-1", name: "New personal injury file", appliesTo: "personal_injury", tasks: ["Open matter file and assign matter number", "Send engagement letter for signature", "Request medical records authorization", "Request police/incident report", "Calendar statute of limitations deadline"] },
  { id: "tpl-2", name: "New employment file", appliesTo: "employment", tasks: ["Open matter file and assign matter number", "Send engagement letter for signature", "Request employment records and correspondence", "Confirm administrative filing deadlines", "Calendar filing deadline"] },
  { id: "tpl-3", name: "Initial consultation", appliesTo: "both", tasks: ["Confirm consultation time with client", "Send preparation instructions", "Prepare consultation question list", "Record consultation outcome", "Follow up within 48 hours"] },
  { id: "tpl-4", name: "Demand package", appliesTo: "both", tasks: ["Compile supporting documentation", "Draft demand letter", "Internal review of demand letter", "Send demand letter", "Calendar response follow-up date"] },
  { id: "tpl-5", name: "Pleadings preparation", appliesTo: "both", tasks: ["Draft complaint", "Internal review of complaint", "File complaint with court", "Confirm service of process", "Calendar defendant's response deadline"] },
  { id: "tpl-6", name: "Discovery preparation", appliesTo: "both", tasks: ["Draft written discovery requests", "Serve discovery requests", "Calendar response deadlines", "Prepare client for deposition", "Review opposing party's discovery responses"] },
  { id: "tpl-7", name: "Mediation preparation", appliesTo: "both", tasks: ["Confirm mediator and venue", "Draft mediation brief", "Prepare settlement range with client", "Compile exhibits", "Debrief client after mediation"] },
  { id: "tpl-8", name: "File closing", appliesTo: "both", tasks: ["Confirm final resolution and disbursement", "Send closing letter to client", "Archive matter documents", "Close client portal access", "Update matter status to Closed"] },
];
